## 1. Introduction to Numpy

Numpy is the most basic and a powerful package for working with data in python.

## 2. How to create a numpy array?

In [5]:
import numpy as np
list1 = [1,2,3,4,5]
arrid = np.array(list1)

print(arrid)
print(type(arrid))

plus = arrid + 10
print(plus)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[11 12 13 14 15]


In [6]:
list2 = [[1,2,4], [4,5,6], [7,8,9]]
arr2d = np.array(list2)
print(arr2d)

[[1 2 4]
 [4 5 6]
 [7 8 9]]


In [7]:
arr2d_f = np.array(list2, dtype = float)
print(arr2d_f)

[[1. 2. 4.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [8]:
print(arr2d_f.astype('int'))

[[1 2 4]
 [4 5 6]
 [7 8 9]]


In [9]:
To_str = (arr2d_f.astype('int').astype('str'))
print(To_str)

[['1' '2' '4']
 ['4' '5' '6']
 ['7' '8' '9']]


In [10]:
arr2d_b = np.array([1,2,3,4,5], dtype= 'bool')
print(arr2d_b)

[ True  True  True  True  True]


In [16]:
arrid_obj = np.array([1, 'One', 2, 'Two'], dtype= object)
print(arrid_obj)
print(type(arrid_obj))

[1 'One' 2 'Two']
<class 'numpy.ndarray'>


In [14]:
arrid_obj_pylist = arrid_obj.tolist()
print(arrid_obj_pylist)
print(type(arrid_obj_pylist))

[1, 'One', 2, 'Two']
<class 'list'>


## 3. How to inspect the size and shape of a numpy array?

In [18]:
list3 = [[1,2,3,5], [4,5,6,5], [7,8,9,5]]
arr2 = np.array(list3, dtype = float)
print(arr2)

[[1. 2. 3. 5.]
 [4. 5. 6. 5.]
 [7. 8. 9. 5.]]


In [30]:
print('shape ' + str(arr2.shape))
print('Data Type ' + str(arr2.dtype))
print('Size ', str(arr2.size))
print('Num Dimentions', str(arr2.ndim))


shape (3, 4)
Data Type float64
Size  12
Num Dimentions 2


## 4. How to extract specific items from an array?

In [47]:
arr2_ext = arr2[:2, :2]
print(arr2_ext)

[[1. 2.]
 [4. 5.]]


In [59]:
b = arr2 > 4
c = arr2 < 4
print(arr2[b])
print(arr2[c])

[5. 5. 6. 5. 7. 8. 9. 5.]
[1. 2. 3.]


## 4.1 How to reverse the rows and the whole array?

In [64]:
# Reverse only the row positions
rev = arr2[::-1,]
print(rev)
arr2

[[7. 8. 9. 5.]
 [4. 5. 6. 5.]
 [1. 2. 3. 5.]]


array([[1., 2., 3., 5.],
       [4., 5., 6., 5.],
       [7., 8., 9., 5.]])

In [65]:
# Reverse the row and column positions
rev_rc = arr2[::-1, ::-1]
print(rev_rc)

[[5. 9. 8. 7.]
 [5. 6. 5. 4.]
 [5. 3. 2. 1.]]


In [68]:
# Reverse the column
rev_c = arr2[::, ::-1]
print(rev_c)
arr2

[[5. 3. 2. 1.]
 [5. 6. 5. 4.]
 [5. 9. 8. 7.]]


array([[1., 2., 3., 5.],
       [4., 5., 6., 5.],
       [7., 8., 9., 5.]])

## 4.2 How to represent missing values and infinite?

In [71]:
missing = arr2
missing[1,1] = np.nan
missing[1,2] = np.inf
missing[2,3] = np.inf
print(missing)

[[ 1.  2.  3.  5.]
 [ 4. nan inf  5.]
 [ 7.  8. inf inf]]


In [75]:
missing_bool = np.isnan(missing) |  np.isinf(missing)
missing[missing_bool] = -1
print(missing)

[[ 1.  2.  3.  5.]
 [ 4. -1. -1.  5.]
 [ 7.  8. -1. -1.]]


## 4.3 How to compute mean, min, max on the ndarray?

In [78]:
# mean, max and min
print('Mean value is ' , str(arr2.mean()))
print('Max value is ', str(arr2.max()))
print('Min value is ', str(arr2.min()))

Mean value is  2.5833333333333335
Max value is  8.0
Min value is  -1.0


In [85]:
# Row wise and column wise min
print('Column wise min ', str(np.amin(arr2,axis=0)))
print('Row wise min ', str(np.amin(arr2, axis=0)))

# Cumulative Sum

print(np.cumsum(arr2))

Column wise min  [ 1. -1. -1. -1.]
Row wise min  [ 1. -1. -1. -1.]
[ 1.  3.  6. 11. 15. 14. 13. 18. 25. 33. 32. 31.]


## 5. How to create a new array from an existing array?

In [123]:
arr2a = arr2[:2,:2]
arr2a[:1,:1] = 100
print(arr2)

[[100.   2.   3.   5.]
 [  4.  -1.  -1.   5.]
 [  7.   8.  -1.  -1.]]


In [122]:
arr2b = arr2[:2, :2].copy()
arr2b[:1, :1] = 101
print(arr2b)

[[101.   2.]
 [  4.  -1.]]


## 6. Reshaping and Flattening Multidimensional arrays

In [121]:
# Reshape a 3x4 array to 4x3 array

print(arr2.reshape(4,3))

[[200.   2.   3.]
 [  5.   4.  -1.]
 [ -1.   5.   7.]
 [  8.  -1.  -1.]]


## 6.1 What is the difference between flatten() and ravel()?

In [109]:
# Flatten it to a 1d array
print(arr2.flatten())

[100.   2.   3.   5.   4.  -1.  -1.   5.   7.   8.  -1.  -1.]


In [120]:
# Changing the flattened array does not change parent
b1 = arr2.flatten()
b1[0] = 200
print(arr2)

[[200.   2.   3.   5.]
 [  4.  -1.  -1.   5.]
 [  7.   8.  -1.  -1.]]


In [119]:
# Changing the raveled array changes the parent also.
b2 = arr2.ravel()
b2[0] = 200
print(arr2)

[[200.   2.   3.   5.]
 [  4.  -1.  -1.   5.]
 [  7.   8.  -1.  -1.]]


## 7. How to create sequences, repetitions and random numbers using numpy?

In [156]:
print(np.arange(2,31,2))
print(np.arange(1,11))
print(np.arange(20,0,-2))
print(np.arange(50,28,-2))

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 1  2  3  4  5  6  7  8  9 10]
[20 18 16 14 12 10  8  6  4  2]
[50 48 46 44 42 40 38 36 34 32 30]


In [159]:
x = np.linspace(start=1, stop=50, num=10, dtype=int)
print(x)

[ 1  6 11 17 22 28 33 39 44 50]


In [170]:
np.set_printoptions(precision= 2)
y = np.logspace(start=1, stop=50, num=10, base=10)
print(y)

[1.00e+01 2.78e+06 7.74e+11 2.15e+17 5.99e+22 1.67e+28 4.64e+33 1.29e+39
 3.59e+44 1.00e+50]


In [175]:
print(np.zeros([5,5], dtype=int))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [173]:
z = np.ones([5,5], dtype=int)
print(z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 7.1 How to create repeating sequences?
### .repeat() , .tile()

In [184]:
# Repeat whole of 'a' two times
a = [1,2,3]
print(np.tile(a,10))

# Repeat each element of 'a' two times
print(np.repeat(a,10))

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
[1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3]


## 7.2 How to generate random numbers?

In [193]:
print(np.random.rand(2,2))

[[0.1  0.67]
 [0.11 0.27]]


In [192]:
print(np.random.randn(2,2))

[[ 0.31  0.37]
 [-0.46  1.63]]


In [214]:
print(np.random.randint(0, 100, size=[4,4]))

[[95 75 86 78]
 [51 16 19 88]
 [78 56 32  8]
 [43 76 66 57]]


In [225]:
# One random number between [0,1]
print(np.random.random())

0.05347255961761843


In [235]:
# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

[[0.31 0.27]
 [0.26 0.61]]


In [252]:
# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a','e','i','o','u'], size = 10))

['i' 'u' 'a' 'e' 'a' 'u' 'u' 'o' 'a' 'u']


In [273]:
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a','e','i','o','u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1]))


['o' 'a' 'o' 'e' 'o' 'o' 'o' 'a' 'o' 'i']


In [282]:
# Create the random state
rn = np.random.RandomState(100)
# Create random numbers between [0,1) of shape 2,2
print(rn.rand(2,2))

[[0.54 0.28]
 [0.42 0.84]]


In [298]:
np.random.seed(100)
print(np.random.rand(2,2))

[[0.54 0.28]
 [0.42 0.84]]


## 7.3 How to get the unique items and the counts?

In [300]:
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [307]:
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)
print(uniqs)
print(counts)

[0 2 3 4 5 7 8]
[1 2 1 1 1 2 2]
